[pyprland]

plugins = [
    "expose",
    "fetch_client_menu",
    "layout_center",
    "toggle_special",
    "wallpapers",
    "scratchpads"
]

[layout_center]
margin = 60
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"

[wallpapers]
path = "~/Images/walls/"
interval = 60
recurse = true
command = '~/.local/bin/hyprland/set_wal "[file]"' 
clear_command = '~/.local/bin/hyprland/clear_wal'


[scratchpads.dropdown_calc]
match_by = "class"
animation = "fromTop"
# command = "st -c dropdown.calc -e R"
command = "kitty --app-id=dropdown.calc -e R"
class = "dropdown.calc"
size = "40% 30%"
max_size = "1920px 100%"
margin = 100

[scratchpads.dropdown_term]
match_by = "class"
animation = "fromTop"
# command = "st -c dropdown.st"
command = "kitty --app-id=dropdown.term"
class = "dropdown.term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.dropdown_notes]
match_by = "class"
animation = "fromTop"
# command = "st -c dropdown.notes -e zk edit --interactive -W ~/Documents/cloud/ZK"
command = "kitty --app-id=dropdown.notes -e zk edit --interactive -W ~/Documents/cloud/ZK"
class = "dropdown.notes"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.dropdown_btop]
match_by = "class"
animation = "fromTop"
# command = "st -c dropdown.btop -e btop"
command = "kitty --app-id=dropdown.btop -e btop"
class = "dropdown.btop"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.dropdown_music]
match_by = "class"
animation = "fromTop"
# command = "st -c dropdown.music -e ncmpcpp"
command = "kitty --app-id=dropdown.music -e ncmpcpp"
class = "dropdown.music"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
